export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_OWNER: "SET_OWNER",
    SET_SELECTEDPLAYLISTID: "SET_SELECTEDPLAYLISTID",
    SET_INFOPLAYLIST: "SET_INFOPLAYLIST",
    SET_CURRENT_PLAYING_TRACK: "SET_CURRENT_PLAYING_TRACK",
    SET_CURRENT_PLAYING_NO_API: "SET_CURRENT_PLAYING_NO_API",
    SET_ID_PLAYLIST_NO_API: "SET_ID_PLAYLIST_NO_API",
    SET_MY_PLAYLIST_NO_API: "SET_MY_PLAYLIST_NO_API",
    SET_INFO_NAME_PLAYLIST: "SET_INFO_NAME_PLAYLIST",
    SET_INDEX_SONG: "SET_INDEX_SONG",
    SET_CHANGE_PLAYLIST_PLAYING: "SET_CHANGE_PLAYLIST_PLAYING",
}